spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    #    url: jdbc:h2:mem:test
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://codestates-mainpj-mysql.clwvdgya13lr.ap-northeast-2.rds.amazonaws.com:3306/preproject_stackoverflow
    username: admin
    password: ${RDS_PASSWORD}
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none  # (1) 스키마 자동 생성 X
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
  sql:
    init:
#      data-locations: classpath*:db/h2/data.sql
#      data-locations: classpath*:db/mariadb/data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
jwt:
  secret-key: ${JWT_SECRET_KEY}           # 민감한 정보는 시스템 환경 변수에서 로드한다.
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
mail:
  address:
    admin: admin@gmail.com